name: GBDK-2020 Build and Package Windows

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events
  # push:
  #   branches: [ build ]
  # pull_request:
  #   branches: [ build ]

jobs:
  build:
    name: Windows-x64
    runs-on: windows-2019
    steps:

      # ==== Set up Tools and Sources ====
      - name: Windows-x64 Depends (sdcc)
        run: |
          curl -Lo sdcc.zip 'https://github.com/bbbbbr/gbdk-2020/releases/download/sdcc_12539/sdcc-snapshot-x86_64-w64-mingw32-20210711-12539.zip'
          7z x sdcc.zip
          
      - name: Windows Depends MSYS2/MinGW64
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: minimal #strict
          release: false
          update: false
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain

      - name: Check out GBDK-2020
        uses: actions/checkout@v2
        with:
          path: gbdk-2020
          submodules: false
      
      # ==== Pre-Build: Set environment vars ====
      # Needs to be in a separate step than build so that setting the environment var takes effect
      - name: Pre-Build setup
        shell: bash        
        run: |
          echo "BUILD_PACKAGE_FILENAME=gbdk-2020-${{ matrix.name }}.zip" >> $GITHUB_ENV          

      # ==== Run GBDK Build ====
      - name: Build GBDK-2020
        shell: cmd
        run: |
          set SDCCDIR=%CD%\sdcc
          cd gbdk-2020
          msys2 -c 'make'
          # make
          cd ..

      # ==== Packaging ====
      - name: Package the Build
        shell: cmd
        run: |
          cd gbdk-2020
          mkdir package
          cd build          
          7z a ../package/${{ env.BUILD_PACKAGE_FILENAME }} gbdk
          cd ..
          cd ..

      - name: Store the Build
        if: (matrix.name == 'Linux-64') || (matrix.name == 'MacOS-64') || ('Windows-x64')
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }} build
          path: gbdk-2020/package/${{ env.BUILD_PACKAGE_FILENAME }}
