# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Default branch only: Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          # - macos-10.15
          # - windows-2019
        include:
          - os: ubuntu-20.04
            name: Linux-64
          # - os: macos-10.15
          #   name: Mac-64
          # - os: windows-2019
          #   name: Windows-64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:

      - name: Linux Depends
        if: matrix.name == 'Linux-64'
        run: |
          curl -Lo sdcc-src-4.1.0.tar.bz2 'https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/4.1.0/sdcc-4.1.0-amd64-unknown-linux2.5.tar.bz2/download'
          bunzip2 sdcc-src-4.1.0.tar.bz2
          tar xvf sdcc-src-4.1.0.tar

      - name: Check out GBDK-2020
        uses: actions/checkout@v2
        with:
          path: gbdk-2020
          submodules: false # This is intentionally not "recursive", change if needed

      - name: Build GBDK-2020
        if: matrix.name == 'Linux-64'
        shell: bash
        run: |
          export SDCCDIR=`pwd`/sdcc
          cd gbdk-2020
          make
          cd ..

      - name: Package build
        if: matrix.name == 'Linux-64'
        shell: bash
        run: |
          cd gbdk-2020
          mkdir package
          cd build
          tar czf ../package/gbdk-2020-Linux.tar.gz gbdk
          cd ..
          cd ..

      - name: Store build
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }} build
          path: gbdk-2020/package/gbdk-2020-Linux.tar.gz
